spring:
  http:
    encoding:
      charset:  UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8
    
### 채팅방 정보 ###
chatroom: 
  list:
    - item:
        id: test1
        name: 테스트방1
    - item:
        id: test2
        name: 테스트방2
    - item:
        id: test3
        name: 테스트방3

### 웹소켓 정보 ###
websocket:
  prefix:
    broker: /topic
    destination: /app
  endpoint:
    sockjs: /sockjs