spring:
#  servlet:
#    multipart:
#      enabled: true
#      file-size-threshold: 2KB
#      max-file-size: 200MB
#      max-request-size: 215MB
  http:
    encoding:
      charset:  UTF-8
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
server:
  port: 3000
  tomcat:
    uri-encoding: UTF-8


file:
  upload-dir: ./src/main/webapp/image

### 채팅방 정보 ###
chatroom: 
  list:
    - item:
        icon: react
        id: react
        name: 리액트
    - item:
        icon: vuejs
        id: vuejs
        name: 뷰
    - item:
        icon: angular
        id: angular
        name: 앵귤러
    - item:
        icon: nodejs
        id: nodejs
        name: NodeJs
    - item:
        icon: ember
        id: ember
        name: 엠바


### 웹소켓 정보 ###
websocket:
  prefix:
    broker: /topic
    destination: /app
  endpoint:
    sockjs: /sockjs